import React from "react";
import { Seo, SectionHeading } from "../components/ui";

const BLOCKS = {
  privacy: {
    title: "Privacy Policy",
    kicker: "LEGAL",
    intro: "This placeholder Privacy Policy explains, in plain terms, how NEXORA handles information submitted through this website. Replace bracketed placeholders with your finalized legal details before production use.",
    sections: [
      ["Information we collect", "When you submit a quote, contact or booking form, we collect the details you provide (such as name, business, email, WhatsApp number and project requirements) so we can respond to you."],
      ["How we use it", "We use your information only to respond to your enquiry, prepare estimates, and deliver services you request. We do not sell your data."],
      ["Analytics", "We may use privacy-conscious analytics to understand how the site is used (e.g. which pages and buttons are popular). We do not collect unnecessary sensitive information."],
      ["Email", "Quote and contact notifications are sent to our team via our email provider. Confirmation emails may be sent to you."],
      ["Data requests", "You may request access to or deletion of the information you submitted by contacting us at [business email]."],
      ["Contact", "For any privacy questions, reach us at [business email] or via WhatsApp."],
    ],
  },
  terms: {
    title: "Terms of Service",
    kicker: "LEGAL",
    intro: "These placeholder Terms outline the basic understanding for using this website and engaging NEXORA. Replace bracketed placeholders with your finalized legal details before production use.",
    sections: [
      ["Services", "NEXORA provides website development and related digital and printing services. Specific deliverables, timelines and costs are agreed per project."],
      ["Estimates", "Prices shown are starting ranges and estimates generated by our configurator. A fixed quote is confirmed before work begins."],
      ["Separate costs", "Domain, hosting, paid APIs, third-party services, payment-provider fees, ad budgets and printing material/installation/delivery are billed separately."],
      ["No guarantees", "We do not guarantee rankings, traffic, leads, sales or revenue. Outcomes depend on many factors outside our control."],
      ["Payments", "Payment terms are agreed per project. Online payments are processed by a third-party provider; we never store card data."],
      ["Intellectual property", "Ownership of final deliverables transfers as agreed in your project terms, typically upon full payment."],
      ["Contact", "Questions about these terms? Contact us at [business email] or via WhatsApp."],
    ],
  },
};

export default function Legal({ kind }) {
  const b = BLOCKS[kind];
  return (
    <div className="pt-28">
      <Seo title={b.title} description={`${b.title} for NEXORA.`} />
      <div className="container-nx max-w-3xl">
        <SectionHeading kicker={b.kicker} title={b.title} />
        <p className="mt-5 text-fog/80 leading-relaxed">{b.intro}</p>
        <div className="mt-10 space-y-8">
          {b.sections.map(([h, p]) => (
            <div key={h}>
              <h3 className="font-display text-lg text-chrome">{h}</h3>
              <p className="mt-2 text-fog/75 leading-relaxed">{p}</p>
            </div>
          ))}
        </div>
        <p className="mt-12 text-xs text-muted/60">Last updated: {new Date().toLocaleDateString()}. This is a placeholder document and not legal advice.</p>
      </div>
    </div>
  );
}
